import type { Product } from "./types.js";

/**
 * Tentaciones AI Commerce — Reference Demo Catalog (DEMO DATA)
 * Real-world fashion, apparel, footwear and accessories inventory for demonstration.
 */
export const TENTACIONES_DEMO_CATALOG: readonly Product[] = [
  {
    id: "prod-polera-essential",
    slug: "polera-oversized-cotton-essential",
    name: "Polera Oversized Organic Cotton Essential",
    brand: "Tentaciones Atelier",
    category: "poleras",
    subcategory: "casual",
    description: "Polera corte oversized confeccionada en 100% algodón orgánico peinado de 240 GSM. Acabado suave y cuello ribeteado de alta durabilidad.",
    basePriceCLP: 22990,
    basePriceEUR: 24.99,
    currency: "CLP",
    tags: ["polera", "t-shirt", "algodon", "oversized", "blanca", "negra", "basico"],
    arAvailable: true,
    defaultArUrn: "urn:tentaciones:ar:apparel:polera-essential",
    image: "/assets/products/polera-essential.svg",
    specifications: {
      material: "100% Algodón Orgánico 240g",
      fit: "Oversized Unisex",
      origin: "Santiago Studio",
      lavado: "Lavado a máquina 30°C",
    },
    variants: [
      { sku: "POL-WHT-S", color: "Blanco Crudo", size: "S", priceCLP: 22990, priceEUR: 24.99, stock: 25, arAssetUrn: "urn:tentaciones:ar:apparel:polera-essential" },
      { sku: "POL-WHT-M", color: "Blanco Crudo", size: "M", priceCLP: 22990, priceEUR: 24.99, stock: 30, arAssetUrn: "urn:tentaciones:ar:apparel:polera-essential" },
      { sku: "POL-WHT-L", color: "Blanco Crudo", size: "L", priceCLP: 22990, priceEUR: 24.99, stock: 20, arAssetUrn: "urn:tentaciones:ar:apparel:polera-essential" },
      { sku: "POL-BLK-M", color: "Negro Carbón", size: "M", priceCLP: 22990, priceEUR: 24.99, stock: 35, arAssetUrn: "urn:tentaciones:ar:apparel:polera-essential" },
      { sku: "POL-BLK-L", color: "Negro Carbón", size: "L", priceCLP: 22990, priceEUR: 24.99, stock: 25, arAssetUrn: "urn:tentaciones:ar:apparel:polera-essential" },
    ],
  },
  {
    id: "prod-camisa-lino",
    slug: "camisa-lino-italiano-breeze",
    name: "Camisa Resort Lino Italiano Breeze",
    brand: "Tentaciones Atelier",
    category: "camisas",
    subcategory: "formal-casual",
    description: "Camisa de corte relajado elaborada en lino italiano prelavado con cuello cubano y botones de nácar natural.",
    basePriceCLP: 45990,
    basePriceEUR: 49.99,
    currency: "CLP",
    tags: ["camisa", "lino", "verano", "resort", "beige", "elegante", "fiesta"],
    arAvailable: true,
    defaultArUrn: "urn:tentaciones:ar:apparel:camisa-lino",
    image: "/assets/products/camisa-lino.svg",
    specifications: {
      material: "100% Lino Italiano",
      fit: "Relaxed Cuban Collar",
      transpirabilidad: "Ultra Alta",
      cuidado: "Secado a la sombra",
    },
    variants: [
      { sku: "CAM-BGE-S", color: "Beige Arena", size: "S", priceCLP: 45990, priceEUR: 49.99, stock: 12, arAssetUrn: "urn:tentaciones:ar:apparel:camisa-lino" },
      { sku: "CAM-BGE-M", color: "Beige Arena", size: "M", priceCLP: 45990, priceEUR: 49.99, stock: 18, arAssetUrn: "urn:tentaciones:ar:apparel:camisa-lino" },
      { sku: "CAM-BGE-L", color: "Beige Arena", size: "L", priceCLP: 45990, priceEUR: 49.99, stock: 15, arAssetUrn: "urn:tentaciones:ar:apparel:camisa-lino" },
      { sku: "CAM-BLU-M", color: "Azul Egeo", size: "M", priceCLP: 45990, priceEUR: 49.99, stock: 14, arAssetUrn: "urn:tentaciones:ar:apparel:camisa-lino" },
    ],
  },
  {
    id: "prod-poleron-hoodie",
    slug: "hoodie-heavyweight-french-terry",
    name: "Hoodie Heavyweight French Terry 450 GSM",
    brand: "Tentaciones Urban",
    category: "polerones",
    subcategory: "streetwear",
    description: "Polerón con capucha estructurado sin cordones, confeccionado en algodón French Terry de 450 GSM de máxima densidad y calidez.",
    basePriceCLP: 49990,
    basePriceEUR: 54.99,
    currency: "CLP",
    tags: ["poleron", "hoodie", "abrigo", "streetwear", "gris", "invierno", "algodon"],
    arAvailable: true,
    defaultArUrn: "urn:tentaciones:ar:apparel:hoodie-heavyweight",
    image: "/assets/products/hoodie.svg",
    specifications: {
      material: "100% Algodón French Terry 450g",
      fit: "Boxy Drop-Shoulder",
      capucha: "Doble forro estructurado",
    },
    variants: [
      { sku: "HOD-GRY-S", color: "Gris Melange", size: "S", priceCLP: 49990, priceEUR: 54.99, stock: 15, arAssetUrn: "urn:tentaciones:ar:apparel:hoodie-heavyweight" },
      { sku: "HOD-GRY-M", color: "Gris Melange", size: "M", priceCLP: 49990, priceEUR: 54.99, stock: 22, arAssetUrn: "urn:tentaciones:ar:apparel:hoodie-heavyweight" },
      { sku: "HOD-GRY-L", color: "Gris Melange", size: "L", priceCLP: 49990, priceEUR: 54.99, stock: 18, arAssetUrn: "urn:tentaciones:ar:apparel:hoodie-heavyweight" },
      { sku: "HOD-BLK-M", color: "Negro Mate", size: "M", priceCLP: 49990, priceEUR: 54.99, stock: 20, arAssetUrn: "urn:tentaciones:ar:apparel:hoodie-heavyweight" },
    ],
  },
  {
    id: "prod-chaqueta-running",
    slug: "chaqueta-stormshield-pro-waterproof",
    name: "Chaqueta StormShield Pro Waterproof Running",
    brand: "Tentaciones Sport",
    category: "chaquetas",
    subcategory: "running",
    description: "Chaqueta técnica impermeable ultra-liviana de 2.5 capas con costuras termoselladas y reflectantes 360 grados.",
    basePriceCLP: 89990,
    basePriceEUR: 119.99,
    currency: "CLP",
    tags: ["chaqueta", "impermeable", "running", "waterproof", "deporte", "negra", "outdoor"],
    arAvailable: true,
    defaultArUrn: "urn:tentaciones:ar:apparel:running-jacket-v2",
    image: "/assets/products/chaqueta-running.svg",
    specifications: {
      impermeabilidad: "20,000 mm",
      respirabilidad: "25,000 g/m2/24h",
      peso: "145 gramos",
      packable: true,
    },
    variants: [
      { sku: "SSJ-BLK-S", color: "Negro Noche", size: "S", priceCLP: 89990, priceEUR: 119.99, stock: 15, arAssetUrn: "urn:tentaciones:ar:apparel:running-jacket-v2" },
      { sku: "SSJ-BLK-M", color: "Negro Noche", size: "M", priceCLP: 89990, priceEUR: 119.99, stock: 25, arAssetUrn: "urn:tentaciones:ar:apparel:running-jacket-v2" },
      { sku: "SSJ-BLK-L", color: "Negro Noche", size: "L", priceCLP: 89990, priceEUR: 119.99, stock: 20, arAssetUrn: "urn:tentaciones:ar:apparel:running-jacket-v2" },
    ],
  },
  {
    id: "prod-vestido-seda",
    slug: "vestido-aura-silk-evening-gala",
    name: "Vestido Aura Silk Elegant Dinner Gala",
    brand: "Tentaciones Atelier",
    category: "vestidos",
    subcategory: "gala",
    description: "Vestido midi de noche confeccionado en 100% seda Mulberry pura con caída fluida y silueta entallada.",
    basePriceCLP: 139990,
    basePriceEUR: 189.99,
    currency: "CLP",
    tags: ["vestido", "seda", "elegante", "gala", "cena", "negro", "formal", "fiesta"],
    arAvailable: true,
    defaultArUrn: "urn:tentaciones:ar:apparel:silk-evening-dress",
    image: "/assets/products/vestido-seda.svg",
    specifications: {
      tejido: "100% Seda Mulberry",
      corte: "Tailored Slim A-Line",
      cuidado: "Limpieza en seco especializada",
    },
    variants: [
      { sku: "SED-NOIR-S", color: "Noir Velvet", size: "S", priceCLP: 139990, priceEUR: 189.99, stock: 8, arAssetUrn: "urn:tentaciones:ar:apparel:silk-evening-dress" },
      { sku: "SED-NOIR-M", color: "Noir Velvet", size: "M", priceCLP: 139990, priceEUR: 189.99, stock: 12, arAssetUrn: "urn:tentaciones:ar:apparel:silk-evening-dress" },
      { sku: "SED-NOIR-L", color: "Noir Velvet", size: "L", priceCLP: 139990, priceEUR: 189.99, stock: 6, arAssetUrn: "urn:tentaciones:ar:apparel:silk-evening-dress" },
    ],
  },
  {
    id: "prod-pantalones-cargo",
    slug: "pantalon-cargo-tactico-techwear",
    name: "Pantalón Cargo Táctico Modular Techwear",
    brand: "Tentaciones Urban",
    category: "pantalones",
    subcategory: "techwear",
    description: "Pantalón técnico con tratamiento repelente al agua DWR, 6 bolsillos de acceso rápido y ajuste ergonómico en tobillos.",
    basePriceCLP: 59990,
    basePriceEUR: 64.99,
    currency: "CLP",
    tags: ["pantalon", "cargo", "techwear", "tactico", "negro", "urbano", "resistente"],
    arAvailable: true,
    defaultArUrn: "urn:tentaciones:ar:apparel:pantalon-cargo",
    image: "/assets/products/pantalon-cargo.svg",
    specifications: {
      material: "Ripstop Stretch DWR",
      bolsillos: "6 bolsillos con cierre YKK",
      ajuste: "Tapered Ankle Cinch",
    },
    variants: [
      { sku: "CAR-BLK-30", color: "Negro Stealth", size: 30, priceCLP: 59990, priceEUR: 64.99, stock: 14, arAssetUrn: "urn:tentaciones:ar:apparel:pantalon-cargo" },
      { sku: "CAR-BLK-32", color: "Negro Stealth", size: 32, priceCLP: 59990, priceEUR: 64.99, stock: 20, arAssetUrn: "urn:tentaciones:ar:apparel:pantalon-cargo" },
      { sku: "CAR-BLK-34", color: "Negro Stealth", size: 34, priceCLP: 59990, priceEUR: 64.99, stock: 16, arAssetUrn: "urn:tentaciones:ar:apparel:pantalon-cargo" },
    ],
  },
  {
    id: "prod-falda-plisada",
    slug: "falda-midi-plisada-metalizada",
    name: "Falda Midi Plisada Shimmering",
    brand: "Tentaciones Atelier",
    category: "faldas",
    subcategory: "elegante",
    description: "Falda midi plisada soleil con acabado sutilmente satinado y pretina elástica de terciopelo.",
    basePriceCLP: 39990,
    basePriceEUR: 44.99,
    currency: "CLP",
    tags: ["falda", "plisada", "midi", "elegante", "champagne", "fiesta"],
    arAvailable: true,
    defaultArUrn: "urn:tentaciones:ar:apparel:falda-plisada",
    image: "/assets/products/falda-plisada.svg",
    specifications: {
      material: "Poliéster Satinado Plisado",
      largo: "Midi 78cm",
      cintura: "Elástica Soft Velvet",
    },
    variants: [
      { sku: "FAL-GLD-S", color: "Champagne Gold", size: "S", priceCLP: 39990, priceEUR: 44.99, stock: 10, arAssetUrn: "urn:tentaciones:ar:apparel:falda-plisada" },
      { sku: "FAL-GLD-M", color: "Champagne Gold", size: "M", priceCLP: 39990, priceEUR: 44.99, stock: 15, arAssetUrn: "urn:tentaciones:ar:apparel:falda-plisada" },
    ],
  },
  {
    id: "prod-zapatillas-carbon",
    slug: "pro-carbon-racer-marathon-shoes",
    name: "Zapatillas Pro Carbon Racer Marathon Shoes",
    brand: "Tentaciones Sport",
    category: "calzado",
    subcategory: "running",
    description: "Zapatilla de competición en asfalto con placa completa de fibra de carbono y espuma de retorno de energía.",
    basePriceCLP: 119990,
    basePriceEUR: 149.99,
    currency: "CLP",
    tags: ["calzado", "zapatillas", "running", "marathon", "carbon", "correr", "deporte", "negro"],
    arAvailable: true,
    defaultArUrn: "urn:tentaciones:ar:footwear:pro-carbon-racer",
    image: "/assets/products/carbon-racer.svg",
    specifications: {
      pesoGramos: 198,
      dropMm: 8,
      placa: "Full-Length Carbon Plate",
      amortiguacion: "Superfoam High Energy",
    },
    variants: [
      { sku: "PCR-BLK-39", color: "Black / Stealth", size: 39, priceCLP: 119990, priceEUR: 149.99, stock: 12, arAssetUrn: "urn:tentaciones:ar:footwear:pro-carbon-racer" },
      { sku: "PCR-BLK-40", color: "Black / Stealth", size: 40, priceCLP: 119990, priceEUR: 149.99, stock: 18, arAssetUrn: "urn:tentaciones:ar:footwear:pro-carbon-racer" },
      { sku: "PCR-BLK-41", color: "Black / Stealth", size: 41, priceCLP: 119990, priceEUR: 149.99, stock: 15, arAssetUrn: "urn:tentaciones:ar:footwear:pro-carbon-racer" },
      { sku: "PCR-BLK-42", color: "Black / Stealth", size: 42, priceCLP: 119990, priceEUR: 149.99, stock: 20, arAssetUrn: "urn:tentaciones:ar:footwear:pro-carbon-racer" },
      { sku: "PCR-BLK-43", color: "Black / Stealth", size: 43, priceCLP: 119990, priceEUR: 149.99, stock: 8, arAssetUrn: "urn:tentaciones:ar:footwear:pro-carbon-racer" },
    ],
  },
  {
    id: "prod-calcetines-pack",
    slug: "calcetines-anti-blister-running-3pack",
    name: "Calcetines Anti-Ampollas Running Pro (Pack x3)",
    brand: "Tentaciones Sport",
    category: "accesorios",
    subcategory: "running",
    description: "Pack de 3 pares de calcetines técnicos con soporte de arco plantar, puntera sin costuras y lana merino termorreguladora.",
    basePriceCLP: 19990,
    basePriceEUR: 24.99,
    currency: "CLP",
    tags: ["calcetines", "accesorios", "running", "anti-ampollas", "deporte"],
    arAvailable: false,
    image: "/assets/products/calcetines.svg",
    specifications: {
      material: "45% Lana Merino, 45% Poliamida, 10% Elastano",
      compresion: "Media en Arco Plantar",
    },
    variants: [
      { sku: "ABS-WHT-M", color: "Blanco / Gris", size: "M (39-42)", priceCLP: 19990, priceEUR: 24.99, stock: 50 },
      { sku: "ABS-BLK-M", color: "Negro / Gris", size: "M (39-42)", priceCLP: 19990, priceEUR: 24.99, stock: 60 },
      { sku: "ABS-BLK-L", color: "Negro / Gris", size: "L (43-46)", priceCLP: 19990, priceEUR: 24.99, stock: 40 },
    ],
  },
];
